modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
issueTrackerURL = "https://github.com/Crendgrim/HaloHUD/issues"
license = "LGPL-3.0"

[[mods]]
modId = "halohud"
version = "${version}"
displayName = "Halo HUD"
authors = "Crendgrim"
description = '''
Small halo style indicator around the crosshair for health and hunger.
'''
logoFile = "assets/halohud/icon.png"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.halohud]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.halohud]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range_forge}"
ordering = "NONE"
side = "BOTH"
