modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Crendgrim/HaloHUD/issues"
license = "LGPL-3.0"

[[mods]]
modId = "halohud"
version = "${version}"
displayName = "Halo HUD"
authors = "Crendgrim"
description = '''
Small halo style indicator around the crosshair for health and hunger.
'''
logoFile = "icon.png"
displayTest = "IGNORE_ALL_VERSION"

[[mixins]]
config = "halohud-common.mixins.json"

[[dependencies.halohud]]
modId = "neoforge"
mandatory = true
versionRange = "[20.2.59-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.halohud]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.halohud]]
modId = "yet_another_config_lib"
mandatory = false
versionRange = "[3,)"
ordering = "NONE"
side = "BOTH"
