modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
issueTrackerURL = "https://github.com/Crendgrim/HaloHUD/issues"
license = "LGPL-3.0"

[[mods]]
modId = "halohud"
version = "${version}"
displayName = "Halo HUD"
authors = "Crendgrim"
description = '''
Small halo style indicator around the crosshair for health and hunger.
'''
logoFile = "assets/halohud/icon.png"
displayTest = "IGNORE_ALL_VERSION"

[[mixins]]
config = "halohud-common.mixins.json"

[[dependencies.halohud]]
modId = "neoforge"
mandatory = true
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.halohud]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range_forge}"
ordering = "NONE"
side = "BOTH"

[[dependencies.halohud]]
modId = "yet_another_config_lib_v3"
mandatory = false
versionRange = "${yacl_version_range_neoforge}"
ordering = "NONE"
side = "BOTH"
